baseURL = 'https://ismaelcelis.com/'
languageCode = 'en-us'
title = 'Ismael Celis'
enableRobotsTXT = true
theme = "paper"
[params]
  disableHLJS = true                         # don't use highlight.js
  twitter = 'ismasan'                # twitter.com/YOUR_TWITTER_ID
  github = 'ismasan'                  # github.com/YOUR_GITHUB_ID
  env = 'production'                  # environment: production, development
[related]
  includeNewer = true
  threshold = 10
  toLower = true
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = true
    type = 'basic'
    weight = 100
[author]
  name = "Ismael Celis"
[markup.goldmark.renderer]
  unsafe = true
