baseURL = 'https://ismaelcelis.com/'
languageCode = 'en-us'
title = 'Ismael Celis'
enableRobotsTXT = true
theme = "paper"
[params]
  disableHLJS = true                         # don't use highlight.js
  twitter = 'ismasan'                # twitter.com/YOUR_TWITTER_ID
  github = 'ismasan'                  # github.com/YOUR_GITHUB_ID
  env = 'production'                  # environment: production, development
  related_content_limit = 5           # number of related content to show
[author]
  name = "Ismael Celis"
[markup.goldmark.renderer]
  unsafe = true
